#tap "homebrew/bundle"
#tap "homebrew/services"
#tap "koekeishiya/formulae"
#tap "wix/brew"
#tap "alienator88/cask"
#tap "grishka/grishka"
#tap "jesseduffield/lazydocker"
#tap "localsend/localsend"
#tap "playcover/playcover"
#tap "schappim/ocr"

tap "adoptopenjdk/openjdk"
tap "localstack/tap"


cask_args appdir: "/Applications"

#brew "coreutils"
#brew "findutils"
#brew "diffutils"
#brew "moreutils"
#brew "go"
#brew "rust"
#brew "node"
#brew "pnpm"
#brew "yarn"
#brew "chruby"
#brew "ruby-install"

brew "awscli"
brew "rsync"
brew "ansible"
brew "kubernetes-cli"
brew "minikube"
brew "pyenv"
brew "tfenv"
brew "jenv"
brew "neovim"
brew "mas"
brew "wget"
brew "git-lfs"
brew "localstack-cli"
brew "stow"
brew "bat"
brew "tree"
brew "direnv"
brew "jq"
brew "starship"
brew "zplug"
brew "zsh-completions"
brew "lsd"
brew "fzf"
brew "xz"
brew "ack"

#cask "the-unarchiver"
#cask "keka"
#cask "cyberduck"
#cask "appcleaner"
#cask "maccy"
#cask "whisky"
#cask "utm"
#cask "keepassxc"

cask "pearcleaner"
cask "slack"
cask "transmission"
cask "zoom"
cask "rectangle"
cask "obs"
cask "docker"
cask "notion"
cask "obsidian"
cask "temurin@8"
cask "temurin@11"
cask "temurin@17"
cask "visual-studio-code"
cask "intellij-idea-ce"
cask "pycharm-ce"
cask "dbeaver-community"
cask "postman"
cask "firefox"
cask "google-chrome"
cask "google-drive"
cask "raycast"
cask "keycastr"
cask "iterm2"
cask "spotify"
cask "vlc"
cask "jellyfin-media-player"
cask "microsoft-remote-desktop"
cask "sublime-text"
cask "discord"
cask "cheatsheet"
cask "devtoys"
cask "betterdisplay"
#cask "bartender"
#cask "topnotch"

#rm -f ~/.zcompdump; compinit
#chmod go-w '/opt/homebrew/share'
#chmod -R go-w '/opt/homebrew/share/zsh'
#git lfs install
