#tap "homebrew/bundle"
#tap "homebrew/services"
#tap "koekeishiya/formulae"
#tap "wix/brew"
#tap "alienator88/cask"
#tap "grishka/grishka"
#tap "jesseduffield/lazydocker"
#tap "localsend/localsend"
#tap "playcover/playcover"
#tap "schappim/ocr"

tap "adoptopenjdk/openjdk"
tap "localstack/tap"

cask_args appdir: "/Applications"
brew "ack"
brew "eza"
brew "awscli"
brew "chruby"
brew "coreutils"
brew "findutils"
brew "diffutils"
brew "moreutils"
brew "gawk"
brew "gnu-sed"
brew "gnu-tar"
brew "gnu-time"
brew "gnu-which"
brew "ffmpeg"
brew "gnupg"
brew "grep"
brew "gzip"
brew "neovim"
brew "node"
brew "pnpm"
brew "yarn"
brew "python"
brew "pyenv"
brew "rsync"
brew "ruby-install"
brew "rust"
brew "vim"
brew "wget"
brew "ansible"
brew "tesseract"
brew "go"
brew "kubernetes-cli"
brew "minikube"

brew "tfenv"
brew "jenv"
brew "mas"
brew "git-lfs"
brew "localstack-cli"
brew "stow"
brew "bat"
brew "tree"
brew "direnv"
brew "jq"
brew "starship"
brew "zplug"
brew "zsh-completions"
brew "lsd"
brew "fzf"
brew "postgresql@16"

cask "the-unarchiver"
cask "keka"
cask "cyberduck"
cask "appcleaner"
cask "maccy"
cask "whisky"
cask "utm"
cask "keepassxc"

cask "pearcleaner"
cask "slack"
cask "transmission"
cask "zoom"
cask "rectangle"
cask "obs"
cask "docker"
cask "notion"
cask "obsidian"
cask "temurin@8"
cask "temurin@11"
cask "temurin@17"
cask "visual-studio-code"
cask "intellij-idea-ce"
cask "pycharm-ce"
cask "dbeaver-community"
cask "postman"
cask "firefox"
cask "google-chrome"
cask "google-drive"
cask "raycast"
cask "keycastr"
cask "iterm2"
cask "spotify"
cask "vlc"
cask "jellyfin-media-player"
cask "microsoft-remote-desktop"
cask "sublime-text"
cask "discord"
cask "cheatsheet"
cask "devtoys"
cask "betterdisplay"
#cask "bartender"
#cask "topnotch"

#brew services start postgresql@16
#createuser postgres
#rm -f ~/.zcompdump; compinit
#chmod go-w '/opt/homebrew/share'
#chmod -R go-w '/opt/homebrew/share/zsh'
#git lfs install
